server: port 8190
servlet.context-path: /RestfulAPI

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=boot
    username: postgres
    password: postgres